[project]
name = "global-non-fungible"
authors = ["Global Non-Fungible Team"]
description = "A decentralized platform for global non-fungible bond asset management"
telemetry = false
requirements = []
[contracts.global-bond-registry]
path = "contracts/global-bond-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
